_extends: .github
version-template: $MAJOR.$MINOR
name-template: $NEXT_MINOR_VERSION
tag-template: postgresql-fingerprint-storage-$NEXT_MINOR_VERSION

template: |
  ## What’s Changed

  $CHANGES

  All contributors: $CONTRIBUTORS
